[package]
name = "rust-bluetooth"
version = "0.1.0"
edition = "2021"

[lib]
name = "rust_bluetooth"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.22", features = ["extension-module"] }
